/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPrincipalRouteImport } from './routes/_authenticated/principal'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminPanelSchoolSchoolIdRouteImport } from './routes/admin-panel.school.$schoolId'
import { Route as AuthenticatedPrincipalDetailKindRouteImport } from './routes/_authenticated/principal.detail.$kind'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrincipalRoute = AuthenticatedPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminPanelSchoolSchoolIdRoute =
  AdminPanelSchoolSchoolIdRouteImport.update({
    id: '/school/$schoolId',
    path: '/school/$schoolId',
    getParentRoute: () => AdminPanelRoute,
  } as any)
const AuthenticatedPrincipalDetailKindRoute =
  AuthenticatedPrincipalDetailKindRouteImport.update({
    id: '/detail/$kind',
    path: '/detail/$kind',
    getParentRoute: () => AuthenticatedPrincipalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/principal': typeof AuthenticatedPrincipalRouteWithChildren
  '/admin-panel/school/$schoolId': typeof AdminPanelSchoolSchoolIdRoute
  '/principal/detail/$kind': typeof AuthenticatedPrincipalDetailKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/principal': typeof AuthenticatedPrincipalRouteWithChildren
  '/admin-panel/school/$schoolId': typeof AdminPanelSchoolSchoolIdRoute
  '/principal/detail/$kind': typeof AuthenticatedPrincipalDetailKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/principal': typeof AuthenticatedPrincipalRouteWithChildren
  '/admin-panel/school/$schoolId': typeof AdminPanelSchoolSchoolIdRoute
  '/_authenticated/principal/detail/$kind': typeof AuthenticatedPrincipalDetailKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/admin'
    | '/attendance'
    | '/principal'
    | '/admin-panel/school/$schoolId'
    | '/principal/detail/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/admin'
    | '/attendance'
    | '/principal'
    | '/admin-panel/school/$schoolId'
    | '/principal/detail/$kind'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/attendance'
    | '/_authenticated/principal'
    | '/admin-panel/school/$schoolId'
    | '/_authenticated/principal/detail/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/principal': {
      id: '/_authenticated/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof AuthenticatedPrincipalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin-panel/school/$schoolId': {
      id: '/admin-panel/school/$schoolId'
      path: '/school/$schoolId'
      fullPath: '/admin-panel/school/$schoolId'
      preLoaderRoute: typeof AdminPanelSchoolSchoolIdRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/_authenticated/principal/detail/$kind': {
      id: '/_authenticated/principal/detail/$kind'
      path: '/detail/$kind'
      fullPath: '/principal/detail/$kind'
      preLoaderRoute: typeof AuthenticatedPrincipalDetailKindRouteImport
      parentRoute: typeof AuthenticatedPrincipalRoute
    }
  }
}

interface AuthenticatedPrincipalRouteChildren {
  AuthenticatedPrincipalDetailKindRoute: typeof AuthenticatedPrincipalDetailKindRoute
}

const AuthenticatedPrincipalRouteChildren: AuthenticatedPrincipalRouteChildren =
  {
    AuthenticatedPrincipalDetailKindRoute:
      AuthenticatedPrincipalDetailKindRoute,
  }

const AuthenticatedPrincipalRouteWithChildren =
  AuthenticatedPrincipalRoute._addFileChildren(
    AuthenticatedPrincipalRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedPrincipalRoute: typeof AuthenticatedPrincipalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedPrincipalRoute: AuthenticatedPrincipalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminPanelRouteChildren {
  AdminPanelSchoolSchoolIdRoute: typeof AdminPanelSchoolSchoolIdRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelSchoolSchoolIdRoute: AdminPanelSchoolSchoolIdRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
